spring.application.name=backend
server.port=${PORT:8080}


spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${POSTGRES_DB_USERNAME:postgres.wweavkixtrxxxmazgbgm}
spring.datasource.password=${POSTGRES_DB_PASSWORD:RohitSharma@@2028}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.data-source-properties.prepareThreshold=0

jwt.secret=${JWT_SECRET:ROHITSHARMA95710mohitsharma81075KULDEEPSHARMA95877}


#todo : --------- Local Configuration(For File Storage) -----
storage.local.input-dir=storage/input
storage.local.output-dir=storage/output


#todo : ---- REDIS Related Variables -------
spring.redis.host=localhost
spring.redis.port=6379




#todo : Hikari make the DB connection request faster
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000