spring.application.name=backend
server.port=${PORT:8080}


spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${POSTGRES_DB_USERNAME:postgres.wweavkixtrxxxmazgbgm}
spring.datasource.password=${POSTGRES_DB_PASSWORD:RohitSharma@@2028}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.datasource.hikari.data-source-properties.prepareThreshold=0

jwt.secret=${JWT_SECRET:ROHITSHARMA95710mohitsharma81075KULDEEPSHARMA95877}


storage.local.input-dir=Storage/input
storage.local.output-dir=Storage/output


#todo : ---- REDIS Related Variables -------
# spring.redis.host=localhost
# spring.redis.port=6379




# Optimized Hikari connection pool for JMeter Load Testing
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000